version: '3'
services:
  postgresdb:
    image: ttokei/postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/pgdata
    networks:
      - postgres_net

  metabase:
    image: metabase/metabase:latest
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=${POSTGRES_PASSWORD}
      - MB_DB_HOST=postgresdb
    ports:
      - 3000:3000
    links:
      - postgresdb
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge

volumes:
  postgres_volume:
